package listaCompra.gui;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Irache Mtnez.
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();

        this.setIconImage(new ImageIcon(getClass().getResource("/listaCompra/gui/images/icono.png")).getImage());
        recargarTabla();
    }

    public void recargarTabla() {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jTableTabla.setModel(modeloTabla);
        String[] nombresColumnas = {"X", "Cantidad", "Nombre", "Sección", "Urgente"};
        modeloTabla.setColumnIdentifiers(nombresColumnas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFormulario = new javax.swing.JPanel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelSeccion = new javax.swing.JLabel();
        jComboBoxSeccion = new javax.swing.JComboBox<>();
        jCheckBoxUrgente = new javax.swing.JCheckBox();
        jButtonCesta = new javax.swing.JButton();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabelListaCompra = new javax.swing.JLabel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTableTabla = new javax.swing.JTable();
        jPanelBotonesPie = new javax.swing.JPanel();
        jButtonBorrarSeleccion = new javax.swing.JButton();
        jButtonBorrarLista = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de la compra");
        setBackground(new java.awt.Color(153, 255, 255));

        jPanelFormulario.setBackground(new java.awt.Color(153, 255, 255));
        jPanelFormulario.setForeground(new java.awt.Color(153, 255, 255));

        jLabelCantidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCantidad.setText("Cantidad:");

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNombre.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jTextFieldNombre.setToolTipText("Introducir nombre del producto a añadir a la lista");
        jTextFieldNombre.setCaretColor(new java.awt.Color(0, 0, 51));
        jTextFieldNombre.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        jTextFieldNombre.setName("Nombre"); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelSeccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeccion.setForeground(new java.awt.Color(0, 0, 51));
        jLabelSeccion.setText("Sección:");

        jComboBoxSeccion.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jComboBoxSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Panadería", "Pescadería", "Frutería", "Carnicería", "Charcutería", "Conservas", "Perfumería", "General" }));
        jComboBoxSeccion.setToolTipText("Elegir sección del supermercado");
        jComboBoxSeccion.setName("Sección"); // NOI18N

        jCheckBoxUrgente.setBackground(new java.awt.Color(153, 255, 255));
        jCheckBoxUrgente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxUrgente.setForeground(new java.awt.Color(0, 0, 51));
        jCheckBoxUrgente.setText("Urgente");
        jCheckBoxUrgente.setToolTipText("Indicar si el producto es urgente");
        jCheckBoxUrgente.setName("Urgente"); // NOI18N
        jCheckBoxUrgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUrgenteActionPerformed(evt);
            }
        });

        jButtonCesta.setBackground(new java.awt.Color(153, 255, 255));
        jButtonCesta.setForeground(new java.awt.Color(153, 255, 255));
        jButtonCesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listaCompra/gui/images/cesta_imagen.png"))); // NOI18N
        jButtonCesta.setToolTipText("Pulsar para añadir producto a la lista");
        jButtonCesta.setBorder(null);
        jButtonCesta.setBorderPainted(false);
        jButtonCesta.setContentAreaFilled(false);
        jButtonCesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCestaActionPerformed(evt);
            }
        });

        jSpinnerCantidad.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        jSpinnerCantidad.setToolTipText("Insertar nº de unidades del producto a comprar");
        jSpinnerCantidad.setBorder(null);

        jLabelListaCompra.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabelListaCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelListaCompra.setText("Mi lista de la compra");

        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);
        jPanelFormulario.setLayout(jPanelFormularioLayout);
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                                .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                                .addComponent(jLabelSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxUrgente))))
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtonCesta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabelListaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxUrgente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelListaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTableTabla.setBackground(new java.awt.Color(204, 204, 204));
        jTableTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTabla.setViewportView(jTableTabla);

        jPanelBotonesPie.setBackground(new java.awt.Color(153, 255, 255));

        jButtonBorrarSeleccion.setBackground(new java.awt.Color(153, 255, 255));
        jButtonBorrarSeleccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBorrarSeleccion.setForeground(new java.awt.Color(0, 0, 51));
        jButtonBorrarSeleccion.setText("Borrar Lista");
        jButtonBorrarSeleccion.setToolTipText("Pulsar para borrar todos los productos de la lista");
        jButtonBorrarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarSeleccionActionPerformed(evt);
            }
        });

        jButtonBorrarLista.setBackground(new java.awt.Color(153, 255, 255));
        jButtonBorrarLista.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBorrarLista.setForeground(new java.awt.Color(0, 0, 51));
        jButtonBorrarLista.setText("Borrar Selección");
        jButtonBorrarLista.setToolTipText("Pulsar para borrar los productos seleccionados de la lista");
        jButtonBorrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarListaActionPerformed(evt);
            }
        });

        jButtonImprimir.setBackground(new java.awt.Color(153, 255, 255));
        jButtonImprimir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(0, 0, 51));
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setToolTipText("Pulsar para visualizar lista de productos por pantalla");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesPieLayout = new javax.swing.GroupLayout(jPanelBotonesPie);
        jPanelBotonesPie.setLayout(jPanelBotonesPieLayout);
        jPanelBotonesPieLayout.setHorizontalGroup(
            jPanelBotonesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBorrarLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBorrarSeleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBotonesPieLayout.setVerticalGroup(
            jPanelBotonesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarLista)
                    .addComponent(jButtonBorrarSeleccion)
                    .addComponent(jButtonImprimir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBotonesPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotonesPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jCheckBoxUrgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUrgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxUrgenteActionPerformed

    private void jButtonCestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCestaActionPerformed

    private void jButtonBorrarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarSeleccionActionPerformed

    private void jButtonBorrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarListaActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarLista;
    private javax.swing.JButton jButtonBorrarSeleccion;
    private javax.swing.JButton jButtonCesta;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JCheckBox jCheckBoxUrgente;
    private javax.swing.JComboBox<String> jComboBoxSeccion;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelListaCompra;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSeccion;
    private javax.swing.JPanel jPanelBotonesPie;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableTabla;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
