package listacompra.gui;

import java.awt.Color;
import java.awt.Font;
import java.util.Locale;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import listacompra.dto.Producto;
import listacompra.gui.modelos.ProductosTablaModelo;
import listacompra.gui.modelos.TablaRender;
import listacompra.logica.LogicaListaCompra;
import org.netbeans.validation.api.builtin.stringvalidation.MayusculasValidacion;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author Irache Mtnez.
 */
public class ListaCompra extends javax.swing.JFrame {

    public ListaCompra() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/listacompra/gui/images/icono.png")).getImage());
        refrescarTabla();

        jButtonAnadirProducto.setEnabled(false);
        ValidationGroup grupo = panelValidacion.getValidationGroup();
        grupo.add(jTextFieldNombre, StringValidators.REQUIRE_NON_EMPTY_STRING, new MayusculasValidacion());

        panelValidacion.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (panelValidacion.getProblem() == null) {
                    jButtonAnadirProducto.setEnabled(true);
                } else {
                    jButtonAnadirProducto.setEnabled(false);
                }
            }
        });
    }

    //método para recargar la tabla
    private void refrescarTabla() {
        TablaRender claseRender = new TablaRender();
        JCheckBox casilla = new JCheckBox();
        DefaultCellEditor editorCelda = new DefaultCellEditor(casilla);

        jTableListaCompra.setModel(new ProductosTablaModelo(LogicaListaCompra.getListaProductos()));

        jTableListaCompra.getColumnModel().getColumn(0).setCellEditor(editorCelda);

        jTableListaCompra.setDefaultRenderer(jTableListaCompra.getColumnClass(0), claseRender);

        darFormatoTabla();

    }

    //método para dar formato a la tabla
    private void darFormatoTabla() {

        //establecer fuente, colores y alto de la cabecera
        jTableListaCompra.getTableHeader().setForeground(Color.DARK_GRAY);
        jTableListaCompra.getTableHeader().setFont(new Font("Ink Free", Font.BOLD, 16));
        jTableListaCompra.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));

        //establecer ancho de las columnas
        int[] anchoColumnas = {30, 80, 190, 175, 81};
        jTableListaCompra.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < anchoColumnas.length; i++) {
            jTableListaCompra.getColumnModel().getColumn(i).setPreferredWidth(anchoColumnas[i]);
        }

        //establecer alto de las filas
        jTableListaCompra.setRowHeight(25);

    }

    //método para borrar los datos del formulario tras pulsar el botón Añadir a la Lista (cesta_compra+)
    private void borrarDatosFormulario() {
        jSpinnerCantidad.setValue(1);
        jTextFieldNombre.setText("");
        jComboBoxSeccion.setSelectedIndex(0);
        jCheckBoxUrgente.setSelected(false);
    }

    //método para borrar las filas seleccionadas en la jTable tras pulsar el botón Borrar Seleccionadas
    private void borrarFilas() {
        if (!LogicaListaCompra.listaVacia()) {
            boolean noHayFilasSeleccionadas = true;
            for (int i = 0; i < jTableListaCompra.getRowCount(); i++) {
                if (jTableListaCompra.getValueAt(i, 0).equals(true)) {
                    LogicaListaCompra.borrarProducto(i);
                    noHayFilasSeleccionadas = false;
                }
            }
            if (noHayFilasSeleccionadas == true) {
                JOptionPane.showMessageDialog(this, "No hay filas seleccionadas.",
                        "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                refrescarTabla();
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay productos en la lista.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProducto = new javax.swing.JPanel();
        jLabelCantidad = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelSeccion = new javax.swing.JLabel();
        jComboBoxSeccion = new javax.swing.JComboBox<>();
        jCheckBoxUrgente = new javax.swing.JCheckBox();
        panelValidacion = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jButtonAnadirProducto = new javax.swing.JButton();
        jLabelListaCompra = new javax.swing.JLabel();
        jPanelBotonesPie = new javax.swing.JPanel();
        buttonBorrarSeleccion = new java.awt.Button();
        buttonBorrarLista = new java.awt.Button();
        buttonImprimir = new java.awt.Button();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTableListaCompra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de la compra");
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jPanelProducto.setBackground(new java.awt.Color(204, 255, 255));
        jPanelProducto.setToolTipText("");

        jLabelCantidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(0, 0, 51));
        jLabelCantidad.setText("Cantidad:");

        jSpinnerCantidad.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        jSpinnerCantidad.setToolTipText("Introducir nº unidades a comprar");
        jSpinnerCantidad.setNextFocusableComponent(jTextFieldNombre);

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 51));
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jTextFieldNombre.setToolTipText("Nombre del producto");
        jTextFieldNombre.setCaretColor(new java.awt.Color(0, 0, 51));
        jTextFieldNombre.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        jTextFieldNombre.setName("Nombre"); // NOI18N
        jTextFieldNombre.setNextFocusableComponent(jComboBoxSeccion);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelSeccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeccion.setForeground(new java.awt.Color(0, 0, 51));
        jLabelSeccion.setText("Sección:");

        jComboBoxSeccion.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jComboBoxSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Panadería", "Pescadería", "Frutería", "Carnicería", "Charcutería", "Conservas", "Perfumería", "General" }));
        jComboBoxSeccion.setToolTipText("Sección del supermercado");
        jComboBoxSeccion.setName("Sección"); // NOI18N
        jComboBoxSeccion.setNextFocusableComponent(jCheckBoxUrgente);

        jCheckBoxUrgente.setBackground(new java.awt.Color(204, 255, 255));
        jCheckBoxUrgente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxUrgente.setForeground(new java.awt.Color(0, 0, 51));
        jCheckBoxUrgente.setText("Urgente");
        jCheckBoxUrgente.setToolTipText("Marcar si es urgente");
        jCheckBoxUrgente.setName("Urgente"); // NOI18N
        jCheckBoxUrgente.setNextFocusableComponent(jButtonAnadirProducto);
        jCheckBoxUrgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUrgenteActionPerformed(evt);
            }
        });

        panelValidacion.setForeground(new java.awt.Color(60, 63, 65));
        panelValidacion.setToolTipText("Validación");
        panelValidacion.setOpaque(false);

        jButtonAnadirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listacompra/gui/images/cesta_imagen.png"))); // NOI18N
        jButtonAnadirProducto.setToolTipText("Añadir a la lista");
        jButtonAnadirProducto.setBorder(null);
        jButtonAnadirProducto.setBorderPainted(false);
        jButtonAnadirProducto.setContentAreaFilled(false);
        jButtonAnadirProducto.setNextFocusableComponent(buttonBorrarSeleccion);
        jButtonAnadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirProductoActionPerformed(evt);
            }
        });

        jLabelListaCompra.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabelListaCompra.setForeground(new java.awt.Color(0, 0, 51));
        jLabelListaCompra.setText("Mi lista de la compra");

        javax.swing.GroupLayout jPanelProductoLayout = new javax.swing.GroupLayout(jPanelProducto);
        jPanelProducto.setLayout(jPanelProductoLayout);
        jPanelProductoLayout.setHorizontalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelValidacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addComponent(jLabelSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductoLayout.createSequentialGroup()
                        .addGap(0, 135, Short.MAX_VALUE)
                        .addComponent(jCheckBoxUrgente)
                        .addGap(14, 14, 14))))
            .addGroup(jPanelProductoLayout.createSequentialGroup()
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButtonAnadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabelListaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductoLayout.setVerticalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldNombre)
                    .addComponent(jSpinnerCantidad))
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxUrgente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelValidacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnadirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelListaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBotonesPie.setBackground(new java.awt.Color(204, 255, 255));

        buttonBorrarSeleccion.setBackground(new java.awt.Color(0, 0, 51));
        buttonBorrarSeleccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonBorrarSeleccion.setForeground(new java.awt.Color(153, 255, 255));
        buttonBorrarSeleccion.setLabel("Borrar Selección");
        buttonBorrarSeleccion.setName("Borrar Seleccion"); // NOI18N
        buttonBorrarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarSeleccionActionPerformed(evt);
            }
        });

        buttonBorrarLista.setBackground(new java.awt.Color(0, 0, 51));
        buttonBorrarLista.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonBorrarLista.setForeground(new java.awt.Color(153, 255, 255));
        buttonBorrarLista.setLabel("Borrar Lista");
        buttonBorrarLista.setName("Borrar Lista"); // NOI18N
        buttonBorrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarListaActionPerformed(evt);
            }
        });

        buttonImprimir.setBackground(new java.awt.Color(0, 0, 51));
        buttonImprimir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonImprimir.setForeground(new java.awt.Color(153, 255, 255));
        buttonImprimir.setLabel("Imprimir");
        buttonImprimir.setName("Imprimir"); // NOI18N
        buttonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesPieLayout = new javax.swing.GroupLayout(jPanelBotonesPie);
        jPanelBotonesPie.setLayout(jPanelBotonesPieLayout);
        jPanelBotonesPieLayout.setHorizontalGroup(
            jPanelBotonesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonBorrarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBorrarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBotonesPieLayout.setVerticalGroup(
            jPanelBotonesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBorrarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBorrarSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPaneTabla.setBackground(new java.awt.Color(0, 0, 51));
        jScrollPaneTabla.setForeground(new java.awt.Color(204, 255, 255));

        jTableListaCompra.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jTableListaCompra.setForeground(new java.awt.Color(0, 0, 51));
        jTableListaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "Cantidad", "Nombre", "Sección", "Urgente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaCompra.setToolTipText("Listado de Productos");
        jTableListaCompra.setGridColor(new java.awt.Color(0, 0, 51));
        jTableListaCompra.setMaximumSize(new java.awt.Dimension(375, 0));
        jTableListaCompra.setMinimumSize(new java.awt.Dimension(375, 0));
        jTableListaCompra.setSelectionForeground(new java.awt.Color(0, 0, 51));
        jScrollPaneTabla.setViewportView(jTableListaCompra);
        if (jTableListaCompra.getColumnModel().getColumnCount() > 0) {
            jTableListaCompra.getColumnModel().getColumn(0).setResizable(false);
            jTableListaCompra.getColumnModel().getColumn(1).setResizable(false);
            jTableListaCompra.getColumnModel().getColumn(2).setResizable(false);
            jTableListaCompra.getColumnModel().getColumn(3).setResizable(false);
            jTableListaCompra.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addComponent(jPanelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBotonesPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotonesPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxUrgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUrgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxUrgenteActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    //Botón imprimir
    private void buttonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimirActionPerformed
        JOptionPane.showMessageDialog(this, LogicaListaCompra.crearLista(), "Lista de la Compra",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonImprimirActionPerformed

    //Botón borrar selección
    private void buttonBorrarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarSeleccionActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane,
                "Se eliminaran los productos seleccinados, ¿desea continuar?",
                "Eliminar Productos Seleccionados", JOptionPane.WARNING_MESSAGE,
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            borrarFilas();
        }
    }//GEN-LAST:event_buttonBorrarSeleccionActionPerformed

    //Botón borrar lista completa
    private void buttonBorrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarListaActionPerformed
        if (!LogicaListaCompra.listaVacia()) {

            if (JOptionPane.showConfirmDialog(rootPane,
                    "Se eliminaran todos los productos, ¿desea continuar?",
                    "Eliminar todos los Productos", JOptionPane.WARNING_MESSAGE,
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                LogicaListaCompra.borrarListaProductos();
                refrescarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos para borrar.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonBorrarListaActionPerformed

    //botón Agregar Producto a la tabla (imagen cesta compra +)
    private void jButtonAnadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirProductoActionPerformed

        Producto producto = new Producto(
                (int) jSpinnerCantidad.getValue(),
                jTextFieldNombre.getText(),
                jComboBoxSeccion.getSelectedItem().toString(),
                jCheckBoxUrgente.isSelected()
        );
        LogicaListaCompra.anadirProducto(producto);
        refrescarTabla();
        borrarDatosFormulario();

    }//GEN-LAST:event_jButtonAnadirProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Locale.setDefault(new Locale("es", "ES"));
                new ListaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonBorrarLista;
    private java.awt.Button buttonBorrarSeleccion;
    private java.awt.Button buttonImprimir;
    private javax.swing.JButton jButtonAnadirProducto;
    private javax.swing.JCheckBox jCheckBoxUrgente;
    private javax.swing.JComboBox<String> jComboBoxSeccion;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelListaCompra;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSeccion;
    private javax.swing.JPanel jPanelBotonesPie;
    private javax.swing.JPanel jPanelProducto;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableListaCompra;
    private javax.swing.JTextField jTextFieldNombre;
    private org.netbeans.validation.api.ui.swing.ValidationPanel panelValidacion;
    // End of variables declaration//GEN-END:variables
}
